// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT
  token, created_at, updated_at, user_id, expires_at, revoked_at
FROM
  refresh_tokens
WHERE
  token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshTokenByToken = `-- name: RevokeRefreshTokenByToken :exec
UPDATE 
  refresh_tokens
SET 
  revoked_at = NOW(), 
  updated_at = NOW()
WHERE
  token = $1
`

func (q *Queries) RevokeRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByToken, token)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO
  refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES
  ($1, NOW(), NOW(), $2, $3) RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type SaveRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, saveRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
